module.exports.stations = {
  station: [
    // {
    //   name: "Civil Service College",
    //   abbr: "12TH",
    //   gtfs_latitude: "37.803768",
    //   gtfs_longitude: "-122.271450",
    //   address: "1245 Broadway",
    //   city: "Oakland",
    //   state: "CA",
    //   county: "alameda",
    //   zipcode: "94612"
    // },
    {
      name: "Gurd Shola",
      abbr: "16TH",
      gtfs_latitude: "9.017796",
      gtfs_longitude: "38.815969",
      address: "2000 Mission Street",
      city: "San Francisco",
      county: "sanfrancisco",
      state: "CA",
      zipcode: "94110"
    },
    {
      name: "Hayo Hulet Mazoria",
      abbr: "19TH",
      gtfs_latitude: "9.014878",
      gtfs_longitude: "38.783267",
      address: "1900 Broadway",
      city: "Oakland",
      county: "alameda",
      state: "CA",
      zipcode: "94612"
    },
    {
      name: "Lem Hotel",
      abbr: "24TH",
      gtfs_latitude: "9.018826",
      gtfs_longitude: "38.795442",
      address: "2800 Mission Street",
      city: "San Francisco",
      county: "sanfrancisco",
      state: "CA",
      zipcode: "94110"
    },
    {
      name: "Asco",
      abbr: "ANTC",
      gtfs_latitude: "9.066437",
      gtfs_longitude: "38.693774",
      address: "1600 Slatten Ranch Road",
      city: "Asco",
      county: "Contra Costa",
      state: "CA",
      zipcode: "94509"
    },
    {
      name: "Meganagna",
      abbr: "ASHB",
      gtfs_latitude: "9.020469",
      gtfs_longitude: "38.802403",
      address: "3100 Adeline Street",
      city: "Berkeley",
      county: "alameda",
      state: "CA",
      zipcode: "94703"
    },
    {
      name: "Stadium",
      abbr: "BALB",
      gtfs_latitude: "8.9806034",
      gtfs_longitude: "38.75776050000002",
      address: "401 Geneva Avenue",
      city: "San Francisco",
      county: "sanfrancisco",
      state: "CA",
      zipcode: "94112"
    },
    {
      name: "Urael Church",
      abbr: "BAYF",
      gtfs_latitude: "8.90288",
      gtfs_longitude: "38.738993",
      address: "15242 Hesperian Blvd.",
      city: "San Leandro",
      county: "alameda",
      state: "CA",
      zipcode: "94578"
    },
    {
      name: "Meskel Square",
      abbr: "BERY",
      gtfs_latitude: "9.010229",
      gtfs_longitude: "38.744509",
      address: "925 Berryessa Way",
      city: "San Jose",
      county: "Santa Clara",
      state: "CA",
      zipcode: "95133"
    },
    {
      name: "La Gare",
      abbr: "CAST",
      gtfs_latitude: "9.009413",
      gtfs_longitude: "38.753344",
      address: "3301 Norbridge Dr.",
      city: "Castro Valley",
      county: "alameda",
      state: "CA",
      zipcode: "94546"
    },
    {
      name: "Mexico Square",
      abbr: "CIVC",
      gtfs_latitude: "9.010486",
      gtfs_longitude: "38.742476",
      address: "1150 Market Street",
      city: "San Francisco",
      county: "sanfrancisco",
      state: "CA",
      zipcode: "94102"
    },
    {
      name: "Coca Cola",
      abbr: "COLS",
      gtfs_latitude: "9.021373",
      gtfs_longitude: "38.86339",
      address: "7200 San Leandro St.",
      city: "Oakland",
      county: "alameda",
      state: "CA",
      zipcode: "94621"
    },
    {
      name: "Tor Hailoch",
      abbr: "COLM",
      gtfs_latitude: "9.011424",
      gtfs_longitude: "38.722818",
      address: "365 D Street",
      city: "Colma",
      county: "sanmateo",
      state: "CA",
      zipcode: "94014"
    },
    {
      name: "Merkato",
      abbr: "CONC",
      gtfs_latitude: "9.030556",
      gtfs_longitude: "38.738889",
      address: "1451 Oakland Avenue",
      city: "Merkato",
      county: "contracosta",
      state: "CA",
      zipcode: "94520"
    },
    {
      name: "Ayat 2",
      abbr: "DALY",
      gtfs_latitude: "9.006129",
      gtfs_longitude: "38.89257",
      address: "500 John Daly Blvd.",
      city: "Daly City",
      county: "sanmateo",
      state: "CA",
      zipcode: "94014"
    },
    {
      name: "Kalite",
      abbr: "DBRK",
      gtfs_latitude: "8.896216",
      gtfs_longitude: "38.769924",
      address: "2160 Shattuck Avenue",
      city: "Kalite",
      county: "alameda",
      state: "CA",
      zipcode: "94704"
    },
    {
      name: "Lideta",
      abbr: "DUBL",
      gtfs_latitude: "9.006347",
      gtfs_longitude: "38.731582",
      address: "5801 Owens Dr.",
      city: "Pleasanton",
      county: "alameda",
      state: "CA",
      zipcode: "94588"
    },
    {
      name: "Hayat",
      abbr: "DELN",
      gtfs_latitude: "8.9806034",
      gtfs_longitude: "38.75776050000002",
      address: "6400 Cutting Blvd.",
      city: "Hayat",
      county: "contracosta",
      state: "CA",
      zipcode: "94530"
    },
    {
      name: "Hayat Plaza",
      abbr: "PLZA",
      gtfs_latitude: "8.9806034",
      gtfs_longitude: "38.75776050000002",
      address: "6699 Fairmount Avenue",
      city: "Hayat",
      county: "contracosta",
      state: "CA",
      zipcode: "94530"
    },
    {
      name: "Ayat 1",
      abbr: "EMBR",
      gtfs_latitude: "9.021109",
      gtfs_longitude: "38.870246",
      address: "298 Market Street",
      city: "San Francisco",
      county: "sanfrancisco",
      state: "CA",
      zipcode: "94111"
    },
    {
      name: "Abinet",
      abbr: "FRMT",
      gtfs_latitude: "9.020317",
      gtfs_longitude: "38.733333",
      address: "2000 BART Way",
      city: "Fremont",
      county: "alameda",
      state: "CA",
      zipcode: "94536"
    },
    {
      name: "Merkato",
      abbr: "FTVL",
      gtfs_latitude: "9.030556",
      gtfs_longitude: "38.738889",
      address: "3401 East 12th Street",
      city: "Oakland",
      county: "alameda",
      state: "CA",
      zipcode: "94601"
    },
    {
      name: "Menelik II Square",
      abbr: "GLEN",
      gtfs_latitude: "8.9806034",
      gtfs_longitude: "38.75776050000002",
      address: "2901 Diamond Street",
      city: "San Francisco",
      county: "sanfrancisco",
      state: "CA",
      zipcode: "94131"
    },
    {
      name: "Saris",
      abbr: "HAYW",
      gtfs_latitude: "8.955214",
      gtfs_longitude: "38.772154",
      address: "699 'B' Street",
      city: "Hayward",
      county: "alameda",
      state: "CA",
      zipcode: "94541"
    },
    {
      name: "Lafto",
      abbr: "LAFY",
      gtfs_latitude: "8.949154",
      gtfs_longitude: "38.747267",
      address: "3601 Deer Hill Road",
      city: "Lafto",
      county: "contracosta",
      state: "CA",
      zipcode: "94549"
    },
    {
      name: "Se-Halite Mehret Church",
      abbr: "LAKE",
      gtfs_latitude: "9.011569",
      gtfs_longitude: "38.821521",
      address: "800 Madison Street",
      city: "Oakland",
      county: "alameda",
      state: "CA",
      zipcode: "94607"
    },
    {
      name: "Saint Michael Church",
      abbr: "MCAR",
      gtfs_latitude: "8.969865",
      gtfs_longitude: "38.765916",
      address: "555 40th Street",
      city: "Oakland",
      county: "alameda",
      state: "CA",
      zipcode: "94609"
    },
    {
      name: "CMC 1",
      abbr: "MLBR",
      gtfs_latitude: "8.9806034",
      gtfs_longitude: "38.75776050000002",
      address: "200 North Rollins Road",
      city: "Millbrae",
      county: "sanmateo",
      state: "CA",
      zipcode: "94030"
    },
    {
      name: "Meri / CMC 2",
      abbr: "MLPT",
      gtfs_latitude: "9.016521",
      gtfs_longitude: "38.864804",
      address: "1555 S Milpitas Blvd",
      city: "Milpitas",
      county: "Santa Clara",
      state: "CA",
      zipcode: "95035"
    },
    {
      name: "Sebategna",
      abbr: "MONT",
      gtfs_latitude: "9.021273",
      gtfs_longitude: "38.733341",
      address: "598 Market Street",
      city: "San Francisco",
      county: "sanfrancisco",
      state: "CA",
      zipcode: "94104"
    },
    {
      name: "Atikilt Tera",
      abbr: "NBRK",
      gtfs_latitude: "9.034592",
      gtfs_longitude: "38.746827",
      address: "1750 Sacramento Street",
      city: "Summit",
      county: "alameda",
      state: "CA",
      zipcode: "94702"
    },
    {
      name: "Meshualekia",
      abbr: "NCON",
      gtfs_latitude: "8.9516",
      gtfs_longitude: "38.690368",
      address: "3700 Port Chicago Highway",
      city: "Piyassa",
      county: "contracosta",
      state: "CA",
      zipcode: "94520"
    },
    {
      name: "Lancia",
      abbr: "OAKL",
      gtfs_latitude: "8.991881",
      gtfs_longitude: "38.759298",
      address: "4 Airport Drive",
      city: "Oakland",
      county: "alameda",
      state: "CA",
      zipcode: "94621"
    },
    {
      name: "Gottera 1",
      abbr: "ORIN",
      gtfs_latitude: "8.980677",
      gtfs_longitude: "38.760181",
      address: "11 Camino Pablo",
      city: "CMC",
      county: "contracosta",
      state: "CA",
      zipcode: "94563"
    },
    {
      name: "Gottera 2",
      abbr: "PITT",
      gtfs_latitude: "8.980677",
      gtfs_longitude: "38.760181",
      address: "1700 West Leland Road",
      city: "Lideta",
      county: "contracosta",
      state: "CA",
      zipcode: "94565"
    },
    {
      name: "Nifas Silk",
      abbr: "PCTR",
      gtfs_latitude: "8.991482",
      gtfs_longitude: "38.726673",
      address: "2099 Railroad Avenue",
      city: "Lideta",
      county: "Contra Costa",
      state: "CA",
      zipcode: "94565"
    },
    {
      name: "Saris Geseya",
      abbr: "PHIL",
      gtfs_latitude: "8.956843",
      gtfs_longitude: "38.763848",
      address: "1365 Treat Blvd.",
      city: "Stadium",
      county: "contracosta",
      state: "CA",
      zipcode: "94597"
    },
    {
      name: "Dama Hotel",
      abbr: "POWL",
      gtfs_latitude: "8.952748",
      gtfs_longitude: "38.76132",
      address: "899 Market Street",
      city: "San Francisco",
      county: "sanfrancisco",
      state: "CA",
      zipcode: "94102"
    },
    {
      name: "Abo Church Junction",
      abbr: "RICH",
      gtfs_latitude: "8.9806034",
      gtfs_longitude: "38.75776050000002",
      address: "1700 Nevin Avenue",
      city: "Megenagna",
      county: "contracosta",
      state: "CA",
      zipcode: "94801"
    },
    {
      name: "Kaliti",
      abbr: "ROCK",
      gtfs_latitude: "8.937806",
      gtfs_longitude: "38.763188",
      address: "5660 College Avenue",
      city: "Oakland",
      county: "alameda",
      state: "CA",
      zipcode: "94618"
    },
    // {
    //   name: "San Bruno",
    //   abbr: "SBRN",
    //   gtfs_latitude: "37.637761",
    //   gtfs_longitude: "-122.416287",
    //   address: "1151 Huntington Avenue",
    //   city: "San Bruno",
    //   county: "sanmateo",
    //   state: "CA",
    //   zipcode: "94066"
    // },
    // {
    //   name: "San Francisco International Airport",
    //   abbr: "SFIA",
    //   gtfs_latitude: "37.615966",
    //   gtfs_longitude: "-122.392409",
    //   address: "International Terminal, Level 3",
    //   city: "San Francisco Int'l Airport",
    //   county: "sanmateo",
    //   state: "CA",
    //   zipcode: "94128"
    // },
    // {
    //   name: "San Leandro",
    //   abbr: "SANL",
    //   gtfs_latitude: "37.721947",
    //   gtfs_longitude: "-122.160844",
    //   address: "1401 San Leandro Blvd.",
    //   city: "San Leandro",
    //   county: "alameda",
    //   state: "CA",
    //   zipcode: "94577"
    // },
    // {
    //   name: "South Hayward",
    //   abbr: "SHAY",
    //   gtfs_latitude: "37.634375",
    //   gtfs_longitude: "-122.057189",
    //   address: "28601 Dixon Street",
    //   city: "Hayward",
    //   county: "alameda",
    //   state: "CA",
    //   zipcode: "94544"
    // },
    // {
    //   name: "South San Francisco",
    //   abbr: "SSAN",
    //   gtfs_latitude: "37.664245",
    //   gtfs_longitude: "-122.443960",
    //   address: "1333 Mission Road",
    //   city: "South San Francisco",
    //   county: "sanmateo",
    //   state: "CA",
    //   zipcode: "94080"
    // },
    // {
    //   name: "Union City",
    //   abbr: "UCTY",
    //   gtfs_latitude: "37.590630",
    //   gtfs_longitude: "-122.017388",
    //   address: "10 Union Square",
    //   city: "Union City",
    //   county: "alameda",
    //   state: "CA",
    //   zipcode: "94587"
    // },
    // {
    //   name: "Walnut Creek",
    //   abbr: "WCRK",
    //   gtfs_latitude: "37.905522",
    //   gtfs_longitude: "-122.067527",
    //   address: "200 Ygnacio Valley Road",
    //   city: "Walnut Creek",
    //   county: "contracosta",
    //   state: "CA",
    //   zipcode: "94596"
    // },
    // {
    //   name: "Warm Springs/South Fremont",
    //   abbr: "WARM",
    //   gtfs_latitude: "37.502171",
    //   gtfs_longitude: "-121.939313",
    //   address: "45193 Warm Springs Blvd",
    //   city: "Fremont",
    //   county: "alameda",
    //   state: "CA",
    //   zipcode: "94539"
    // },
    // {
    //   name: "West Dublin/Pleasanton",
    //   abbr: "WDUB",
    //   gtfs_latitude: "37.699756",
    //   gtfs_longitude: "-121.928240",
    //   address: "6501 Golden Gate Drive",
    //   city: "Dublin",
    //   county: "alameda",
    //   state: "CA",
    //   zipcode: "94568"
    // },
    // {
    //   name: "West Oakland",
    //   abbr: "WOAK",
    //   gtfs_latitude: "37.804872",
    //   gtfs_longitude: "-122.295140",
    //   address: "1451 7th Street",
    //   city: "Oakland",
    //   county: "alameda",
    //   state: "CA",
    //   zipcode: "94607"
    // }
  ]
};
